// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozjijrrifxqledgqodzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96amlqcnJpZnhxbGVkZ3FvZHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNDEzODMsImV4cCI6MjA1MDcxNzM4M30.hvViSu8xruMyAk_2x1taJLLhkXiKT4yjk5SFmJHyz1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);